### ISSUE TITLE
Change location pull-down to accomodate long list of states, counties and cities in more appropriate form.

### ISSUE THREAD

**Issue by tonypearson** [Call-for-Code-for-Racial-Justice/Legit-Info#40]
## Background
Current location pull-down menu is single scroll down and is not suitable user experience for a long list of states, cities, and counties 

## Solution
- Update frontend with more suitable UI/UX experience

## Tasks
- Discuss design ideas with us here in the issue
-  Update frontend by changing forms.py under cfc_app and users

Demo of site here: https://legit-info-app.7p7tcbyw0n2.us-south.codeengine.appdomain.cloud/search/

**Comment by tonypearson** [comment]
Re-open for consideration

**Comment by twan-westerhof** [comment]
hi @tonypearson! @rohitkpa and I were looking to help with this issue, and we were trying to log what info came back after submitting the form on /search. We ran into this ValueError as below, and were wondering if you had any suggestions. We followed stage 1 development for setup, and our initial thoughts were to modify forms.py to have multiple dropdowns, narrowing down (country, county, city, state)

![image](https://user-images.githubusercontent.com/70281304/109574844-e41d7a00-7aad-11eb-8ba3-700e44e0c12d.png)

**Comment by tonypearson** [comment]
@twan-westerhof @rohitkpa Let's open this as a new issue please.  #40 will remain for the "new enhancement", and a new issue to handle the "ValueError"

**Comment by reginapizza** [comment]
Hi! I was hoping I could take this issue on for Hacktoberfest if the feature request is still wanted. 

In order to make the search easier, would it be okay to split the location field into two fields- one being a "Select State" which has all 50 states, and a second one being "Select [Closest] City" (or something like that) that renders a list of cities depending on the answer of the state select field? I was thinking the city select field could be either hidden or disabled until the user selects their state. 

What do you think?

**Comment by demilolu** [comment]
This is an interest approach @reginapizza let's discuss with the team: @upkarlidder @tonypearson

**Comment by demilolu** [comment]
and it's also all yours :) @reginapizza

**Comment by upkarlidder** [comment]
Hey @reginapizza, just checking in. We would like to invite you to our Slack http://callforcode.org/slack workspace. Please join the `racial-justice-legit-info`. We meet every Friday.  You can get more details in the slack channel.

@shbhmsxn4 is also able to assist.
